version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    image: postgres
    ports:
      - "5432:5432"
    # Change sample Username password and DB name 
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
